### ISSUE TITLE
Issues with grad calculation in fff loss function

### ISSUE THREAD

**Issue by thelostscout** [vislearn/FFF#5]
If just the `loss.py` is copied to a project that utilises `lightning-trainable` and the `fff_loss` function is utilised, a runtime error occurs in `nll_surrogate` during the calculation of `v2` because all the tensors (x, z, v) do not have `required_grad` enabled.
I suspect this has to do with the validation loop in `lightning-trainable` turning of all the gradients. Don't have time to provide a minimal example right now. Maybe later.

**Comment by thelostscout** [comment]
When wrapping the calculation of the loss in the `with torch.set_grad_enabled(True)` context manager, the issue does not occur. This supports my suspicion about the issue being with the disabling of gradients during the validation loop.
This fix works for now, but I would argue that it is not the intended behaviour.

**Comment by fdraxler** [comment]
Hi, thanks for your interest! The nll *value* returned by the surrogate is meaningless, only its gradient is useful, so don't use it for validation. To compute validation nll, you need to compute the full network Jacobian. I modified the `loss.py` script to contain that computation. Check out the toy-example.ipynb for example usage.
