### ISSUE TITLE
How to implement a conditional version of FFF loss?

### ISSUE THREAD

**Issue by laodar** [vislearn/FFF#6]
Suppose we have a conditonal autoencoder, encoder(x, c) and decoder(z, c), how to compute the latent loss to make it a conditional generative model? Should I add a "feed_condition" function, and call it to set some variable like  self.condition, then compute the latent loss as usual?

**Comment by laodar** [comment]
Thanks for your excellent work. Flow models are very elegant in theory, FFF wil be promising if it is validated on more complex dataset.

**Comment by fdraxler** [comment]
Thanks for your interest! Please our reference implementation here: https://github.com/vislearn/FFF/blob/d692a15125c92fb01d14d1649a1da9af308b2373/fff/base.py#L312C1-L313C1

I am closing this for now, feel free to come back with more questions.

**Comment by laodar** [comment]
> Thanks for your interest! Please our reference implementation here: https://github.com/vislearn/FFF/blob/d692a15125c92fb01d14d1649a1da9af308b2373/fff/base.py#L312C1-L313C1
> 
> I am closing this for now, feel free to come back with more questions.

Thank you for your response. A question that has been bothering me for a long time came to mind. Do you know about this paper: https://openreview.net/pdf?id=H1xwNhCcYm? Do you think removing the invertible network architecture constraint (like your FFF) would improve flow models in this regard? It seems we still don't fully understand why flow models don't know what they don't know.
